nginx:
  build: ./nginx/
  ports:
    - "3000:80"
  links:
    - php
  volumes_from:
    - app

php:
  build: ./php/
  volumes_from:
    - app
  expose:
    - "9000"
  links:
    - mysql

app:
  build: ./
  volumes:
    - ./src:/var/www/html
  command: "true"

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes_from:
    - data
  environment:
    MYSQL_ROOT_PASSWORD: pass
    MYSQL_DATABASE: auth
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

data:
  image: mysql:latest
  volumes:
    - /var/lib/mysql
  command: "true"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - mysql
  environment:
    PMA_HOST: mysql